---
apiVersion: v2
appVersion: 4.37.0
description: Ghost is a blogging and publishing software
name: ghost
version: 2.1.2
kubeVersion: ">=1.19.0-0"
keywords:
  - ghost
  - blogging
home: https://github.com/geek-cookbook/charts/tree/master/charts/stable/ghost
icon: https://ghost.org/images/logos/logo-black-1.png
sources:
  - https://github.com/TryGhost/Ghost
  - https://github.com/TryGhost/Ghost-CLI
maintainers:
  - name: samip5
    email: sm+geek-cookbook+git@samip.fi
dependencies:
  - name: common
    repository: https://library-charts.geek-cookbook.com
    version: 4.5.2
  - name: mariadb
    version: 11.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
